extends: standard
plugins:
  - jsdoc
env:
  es6: true
  browser: true
  node: true
  jquery: true
rules:
  no-multiple-empty-lines: off
  space-before-function-paren:
    - error
    - never
  jsdoc/check-alignment: error
