strictness: high
max-line-length: 120
requirements:
    - requirements-dev.txt
ignore-paths:
    - doc
ignore-patterns:
    - manage.py
    - ^.*urls\.py$  # ignore files "urls.py" because too long lines
uses:
    - django
pylint:
  disable:
    - too-many-ancestors
    - too-many-lines