repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 23.3.0 # needs to be also updated in requirements-dev.txt and .github/workflows/ci.yml
    hooks:
      - id: black
        language_version: python3
