repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0 # needs to be also updated in requirements-dev.txt
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
     - id: trailing-whitespace
       exclude_types: ["svg"]
     - id: end-of-file-fixer
       exclude_types: ["svg"]
     - id: mixed-line-ending
       exclude_types: ["svg"]
       args: ["--fix=lf"]
