repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2  # version 3.4.0 doesn't work with Python 3.7
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 23.3.0 # needs to be also updated in requirements-dev.txt
    hooks:
      - id: black
        language_version: python3
