# -*- coding: utf-8 -*-


def test_edit_tutorial(sel):
    sel.click("//a[contains(text(),'Ajouter  une partie')]")
    sel.wait_for_page_to_load("30000")
    sel.type("id=id_title", "partie &")
    sel.type("id=id_title", "partie 1")
    sel.type("id=id_introduction", "selenium")
    sel.type("id=id_conclusion", "selenium")
    sel.type("id=id_msg_commit", "selenium")
    sel.click("css=button.btn")
    sel.wait_for_page_to_load("30000")
    sel.click("link=Ajouter une section")
    sel.wait_for_page_to_load("30000")
    sel.type("id=id_title", "section 1")
    sel.type("id=id_text", "blablabla")
    sel.type("id=id_msg_commit", "selenium")
    sel.click("name=answer")
    sel.wait_for_page_to_load("30000")
    sel.click(u"link=Éditer")
    sel.wait_for_page_to_load("30000")
    sel.type("id=id_text", "blablablaedit")
    sel.click("name=answer")
    sel.wait_for_page_to_load("30000")
    assert("section 1" == sel.get_text("css=#1-section-1 > a"))
    sel.click("link=Supprimer")
    sel.click("name=delete")
    sel.wait_for_page_to_load("30000")
    sel.click("link=Selenium")
    sel.wait_for_page_to_load("30000")
