# Generated by Django 1.10.8 on 2017-10-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("featured", "0005_auto_20160114_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredresource",
            name="authors",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Auteurs"),
        ),
    ]
