# Generated by Django 1.10.7 on 2017-08-31 10:23


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupcontact",
            name="person_in_charge",
        ),
        migrations.AddField(
            model_name="groupcontact",
            name="persons_in_charge",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Responsables"),
        ),
    ]
