# Generated by Django 2.1.5 on 2019-03-08 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorialv2', '0023_auto_20190114_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishablecontent',
            name='proofreaders',
            field=models.ManyToManyField(db_index=True, related_name='proofreaders', to=settings.AUTH_USER_MODEL, verbose_name='Relecteurs'),
        ),
        migrations.AlterField(
            model_name='publishablecontent',
            name='authors',
            field=models.ManyToManyField(db_index=True, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Auteurs'),
        ),
    ]
