# Generated by Django 2.1.5 on 2019-04-16 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0025_auto_20190415_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationevent",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="date de création"
            ),
            preserve_default=False,
        ),
    ]
