# Generated by Django 2.1.11 on 2019-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0028_auto_20191024_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentcontributionrole",
            name="title",
            field=models.CharField(max_length=80),
        ),
    ]
