# Generated by Django 2.2.16 on 2020-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0030_contentsuggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishablecontent",
            name="source",
            field=models.URLField(blank=True, null=True, verbose_name="Source"),
        ),
    ]
