# Generated by Django 2.2.16 on 2020-09-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialv2', '0031_quizzstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzAvailableAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_label', models.TextField(verbose_name='Intitulé de la réponse')),
                ('is_good', models.BooleanField(default=False, verbose_name='Est une réponse attendue')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='url')),
                ('question', models.TextField(verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='anwser')),
                ('date_answer', models.DateField(auto_now=True, verbose_name='Date of answer')),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorialv2.PublishableContent', verbose_name='Tutoriel lié')),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialv2.QuizzQuestion', verbose_name='Question liée')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizzStat',
        ),
        migrations.AddField(
            model_name='quizzavailableanswer',
            name='related_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialv2.QuizzQuestion', verbose_name='Question liée'),
        ),
    ]
