# Generated by Django 2.2.16 on 2020-09-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0033_quizzuseranswer_full_answer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizzavailableanswer",
            old_name="answer_label",
            new_name="label",
        ),
    ]
