# Generated by Django 3.2.13 on 2022-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0033_move_helpwriting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="Nom")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("position", models.IntegerField(db_index=True, default=0, verbose_name="Position")),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Objectif",
                "verbose_name_plural": "Objectifs",
            },
        ),
        migrations.AddField(
            model_name="publishablecontent",
            name="goals",
            field=models.ManyToManyField(
                blank=True, db_index=True, to="tutorialv2.Goal", verbose_name="Objectifs du contenu"
            ),
        ),
    ]
