# Generated by Django 2.2.17 on 2020-12-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0031_source_is_url"),
        ("tutorialv2", "0034_auto_20200927_1105"),
    ]

    operations = []
