# Generated by Django 2.2.19 on 2021-06-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0034_auto_20200927_1105"),
        ("tutorialv2", "0031_source_is_url"),
    ]

    operations = []
