# Generated by Django 3.2.14 on 2022-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0034_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishablecontent",
            name="goals",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="contents",
                to="tutorialv2.Goal",
                verbose_name="Objectifs du contenu",
            ),
        ),
    ]
