# Generated by Django 2.2.17 on 2021-01-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0035_merge_20201219_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizzquestion",
            name="question_type",
            field=models.TextField(
                db_index=True, default="qcm", editable=False, max_length=15, verbose_name="Type de question"
            ),
        ),
    ]
