# Generated by Django 3.2.15 on 2022-12-21 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0035_alter_publishablecontent_goals"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentsuggestion",
            options={"verbose_name": "Suggestion de contenu", "verbose_name_plural": "Suggestions de contenu"},
        ),
    ]
