# Generated by Django 3.2.15 on 2023-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0036_alter_contentsuggestion_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="Nom")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("position", models.IntegerField(db_index=True, default=0, verbose_name="Position")),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
            },
        ),
        migrations.AddField(
            model_name="publishablecontent",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="contents",
                to="tutorialv2.Label",
                verbose_name="Labels du contenu",
            ),
        ),
    ]
