# Generated by Django 2.2.19 on 2021-06-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialv2', '0036_quizzquestion_question_type'),
        ('tutorialv2', '0035_merge_20210601_1744'),
    ]

    operations = [
    ]
