# Generated by Django 3.2.15 on 2022-10-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0035_alter_publishablecontent_goals"),
        ("tutorialv2", "0037_merge_20210601_1830"),
    ]

    operations = []
