# Generated by Django 3.2.15 on 2023-05-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0037_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedcontent",
            name="search_engine_already_indexed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Déjà indexé par le moteur de recherche"
            ),
        ),
        migrations.AlterField(
            model_name="publishedcontent",
            name="search_engine_flagged",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Doit être (ré)indexé par le moteur de recherche"
            ),
        ),
    ]
