# Generated by Django 3.2.15 on 2023-04-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0037_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="position",
        ),
    ]
