# Generated by Django 3.2.15 on 2023-05-20 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutorialv2", "0037_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claps",
                        related_query_name="clap",
                        to="tutorialv2.publishablecontent",
                        verbose_name="Contenu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claps",
                        related_query_name="clap",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clap",
                "verbose_name_plural": "Claps",
                "unique_together": {("publication", "user")},
            },
        ),
    ]
