# Generated by Django 3.2.15 on 2023-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0038_goals_forbid_unclassified_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedcontent",
            name="char_count",
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="Nombre de lettres du contenu"),
        ),
        migrations.AlterField(
            model_name="publishedcontent",
            name="must_redirect",
            field=models.BooleanField(
                blank=True, db_index=True, default=False, verbose_name="Redirection vers une version plus récente"
            ),
        ),
    ]
