# Generated by Django 3.2.19 on 2023-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorialv2", "0038_goals_forbid_unclassified_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedcontent",
            name="es_already_indexed",
        ),
        migrations.RemoveField(
            model_name="publishedcontent",
            name="es_flagged",
        ),
        migrations.AddField(
            model_name="publishedcontent",
            name="search_engine_already_indexed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Déjà indexé par le moteur de recherche"
            ),
        ),
        migrations.AddField(
            model_name="publishedcontent",
            name="search_engine_flagged",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Doit être (ré)indexé par le moteur de recherche"
            ),
        ),
    ]
