# Generated by Django 4.2.11 on 2024-04-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0039_publishedcontent_typo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedcontent",
            name="es_already_indexed",
        ),
        migrations.RemoveField(
            model_name="publishedcontent",
            name="es_flagged",
        ),
        migrations.AddField(
            model_name="publishedcontent",
            name="search_engine_requires_index",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Doit être (ré)indexé par le moteur de recherche"
            ),
        ),
    ]
