# Generated by Django 4.2.11 on 2024-06-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0040_rename_search_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishablecontent",
            name="must_reindex",
        ),
    ]
