# Generated by Django 4.2.16 on 2025-04-30 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutorialv2", "0042_alter_contentsuggestion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishablecontent",
            name="is_obsolete",
        ),
        migrations.AddField(
            model_name="publishablecontent",
            name="obsolete_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Justification d'obsolescence"),
        ),
        migrations.CreateModel(
            name="PotentialObsolete",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(verbose_name="Message")),
                ("report_date", models.DateTimeField(auto_now_add=True, verbose_name="Date du signalement")),
                (
                    "status",
                    models.CharField(
                        choices=[("nouveau", "Nouveau"), ("traite", "Traité"), ("ignore", "Ignoré")],
                        default="nouveau",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obsolete_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="L’auteur du signalement",
                    ),
                ),
                (
                    "publishable_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obsolete_reports",
                        to="tutorialv2.publishablecontent",
                        verbose_name="Contenu publié",
                    ),
                ),
            ],
        ),
    ]
