# Generated by Django 5.2.8 on 2025-11-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0038_merge_20221030_2030"),
        ("tutorialv2", "0042_alter_contentsuggestion_options_and_more"),
    ]

    operations = []
