# Generated by Django 4.2.16 on 2025-03-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutorialv2", "0042_alter_contentsuggestion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotentialObsolete",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(verbose_name="Message")),
                ("report_date", models.DateTimeField(auto_now_add=True, verbose_name="Date du signalement")),
                (
                    "status",
                    models.CharField(
                        choices=[("nouveau", "Nouveau"), ("traite", "Traité"), ("ignore", "Ignoré")],
                        default="nouveau",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obsolete_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author of the report",
                    ),
                ),
                (
                    "publishable_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obsolete_reports",
                        to="tutorialv2.publishablecontent",
                        verbose_name="Contenu publié",
                    ),
                ),
            ],
        ),
    ]
