# Generated by Django 4.2.16 on 2025-02-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0042_alter_contentsuggestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedcontent",
            name="is_obsolete",
            field=models.BooleanField(default=False),
        ),
    ]
