# Generated by Django 3.2.15 on 2022-09-29 22:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0042_alter_contentsuggestion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareableLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("active", models.BooleanField(default=True)),
                ("expiration", models.DateTimeField(null=True)),
                ("description", models.CharField(default="Lien de partage", max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[("DRAFT", "Lien vers le dernier brouillon"), ("BETA", "Lien vers la dernière bêta")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutorialv2.publishablecontent",
                        verbose_name="Contenu",
                    ),
                ),
            ],
        ),
    ]
