# Generated by Django 5.2.8 on 2025-11-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0043_merge_20251129_1929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizzuseranswer",
            name="answer",
            field=models.TextField(verbose_name="answer"),
        ),
    ]
