# Generated by Django 4.2.16 on 2025-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0043_potentialobsolete"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishablecontent",
            name="obsolete_just",
            field=models.TextField(blank=True, null=True, verbose_name="Justificatif d'obsolescence"),
        ),
    ]
