# Generated by Django 4.2.16 on 2025-04-27 20:08

from django.db import migrations


def update_obsolete_justif(apps, schema_editor):
    PublishableContent = apps.get_model("tutorialv2", "PublishableContent")
    PublishableContent.objects.filter(is_obsolete=True).update(obsolete_reason="Contenu obsolète.")


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0043_obsolete_content"),
    ]

    operations = [
        migrations.RunPython(update_obsolete_justif),
        migrations.RemoveField(
            model_name="publishablecontent",
            name="is_obsolete",
        ),
    ]
