# Generated by Django 4.2.16 on 2025-02-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0043_publishedcontent_is_obsolete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedcontent",
            name="is_obsolete",
            field=models.BooleanField(),
        ),
    ]
