# Generated by Django 5.2.17 on 2026-09-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0043_shareablelink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishablecontent",
            name="pubdate",
        ),
    ]
