# Generated by Django 4.2.16 on 2025-03-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0044_publishablecontent_obsolete_just"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publishablecontent",
            old_name="obsolete_just",
            new_name="obsolete_justif",
        ),
    ]
