# Generated by Django 5.2.8 on 2025-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0044_alter_quizzuseranswer_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizzquestion",
            name="human_readable_name",
            field=models.TextField(default="Question", verbose_name="Nom"),
        ),
    ]
