# Generated by Django 5.2.8 on 2025-12-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0043_shareablelink"),
        ("tutorialv2", "0045_quizzquestion_human_readable_name"),
    ]

    operations = []
