# Generated by Django 4.2.16 on 2025-02-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0046_alter_publishedcontent_is_obsolete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedcontent",
            name="is_obsolete",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Est obsolète"),
        ),
    ]
