# Generated by Django 1.9.8 on 2016-12-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("munin", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS munin_test"),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
            ],
        ),
    ]
