# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_auto_20170619_1854'),
        ('member', '0012_profile_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_staff_badge',
        ),
        migrations.AddField(
            model_name='profile',
            name='hats',
            field=models.ManyToManyField(db_index=True, to='utils.Hat', verbose_name='Casquettes'),
        ),
    ]
