# Generated by Django 1.10.7 on 2017-08-07 19:30


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0012_profile_licence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_hover_enabled",
            field=models.BooleanField(default=False, verbose_name="D\xe9roulement au survol ?"),
        ),
    ]
