# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20170628_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_hover_enabled',
            field=models.BooleanField(default=False, verbose_name='D\xe9roulement au survol ?'),
        ),
    ]
