# Generated by Django 1.10.8 on 2018-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0016_python_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_for_new_mp",
            field=models.BooleanField(default=False, verbose_name="Envoyer pour les nouveaux MP"),
        ),
    ]
