# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_python_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_for_answer',
            field=models.BooleanField(default=False, verbose_name="Recevoir un courriel lors d'une réponse à un message privé"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_hover_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer le déroulement des menus au survol'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_sign',
            field=models.BooleanField(default=True, verbose_name='Afficher les signatures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='use_old_smileys',
            field=models.BooleanField(default=False, verbose_name='Ne pas utiliser les smileys Clem'),
        ),
    ]
