# Generated by Django 3.2.12 on 2022-03-24 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0020_auto_20201018_0841"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="use_old_smileys",
        ),
    ]
