# Generated by Django 3.2.12 on 2022-04-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0021_remove_profile_use_old_smileys"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_forum_activity",
            field=models.BooleanField(
                default=False, verbose_name="Masquer l'activité de forum et les commentaires sur la page de profil"
            ),
        ),
    ]
