# Generated by Django 4.2.16 on 2025-06-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("member", "0022_add_hide_forum_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(db_index=True, unique=True, verbose_name="Adresse IP")),
                (
                    "is_network_address",
                    models.BooleanField(db_index=True, verbose_name="Représente le bloc /64 de l'adresse IP"),
                ),
                ("blocked_date", models.DateTimeField(auto_now_add=True, verbose_name="Date du blocage")),
                ("reason", models.CharField(max_length=250, verbose_name="Raison du blocage")),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse IP bloquée",
                "verbose_name_plural": "Adresses IP bloquées",
            },
        ),
    ]
