# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_python_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='solved_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant noté le sujet comme résolu'),
        ),
    ]
