# Generated by Django 2.2.9 on 2020-03-15 17:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("forum", "0017_auto_20190114_1301"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="ForumCategory",
        ),
    ]
