# Generated by Django 2.2.14 on 2020-08-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0018_auto_20200315_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_potential_spam",
            field=models.BooleanField(default=False, verbose_name="Est potentiellement du spam"),
        ),
    ]
