# Generated by Django 2.2.19 on 2021-03-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0021_remove_post_is_potential_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="github_repository_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom du dépôt GitHub"),
        ),
    ]
