# Generated by Django 4.2.11 on 2024-04-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0023_allow_blank_solved_by_topic_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="es_already_indexed",
        ),
        migrations.RemoveField(
            model_name="post",
            name="es_flagged",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="es_already_indexed",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="es_flagged",
        ),
        migrations.AddField(
            model_name="post",
            name="search_engine_requires_index",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Doit être (ré)indexé par le moteur de recherche"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="search_engine_requires_index",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Doit être (ré)indexé par le moteur de recherche"
            ),
        ),
    ]
