# Generated by Django 4.2.16 on 2024-10-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0024_rename_search_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="update_index_date",
        ),
    ]
