# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_auto_20150416_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatepost',
            name='with_hat',
            field=models.CharField(blank=True, max_length=40, verbose_name='Casquette'),
        ),
    ]
