# Generated by Django 1.10.7 on 2017-09-05 22:20


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0014_auto_20170905_2220"),
        ("mp", "0002_auto_20150416_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatepost",
            name="hat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="privateposts",
                to="utils.Hat",
                verbose_name="Casquette",
            ),
        ),
    ]
