# Generated by Django 1.11.15 on 2019-01-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mp", "0004_python_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatetopic",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="privatetopic",
            name="last_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_message",
                to="mp.PrivatePost",
                verbose_name="Dernier message",
            ),
        ),
    ]
