# Generated by Django 3.2.21 on 2023-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mp", "0007_add_votes_to_private_post"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="privatetopicread",
            constraint=models.UniqueConstraint(fields=("privatetopic", "user"), name="unique_privatetopicread"),
        ),
    ]
