# Generated by Django 2.1.11 on 2019-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_usergallery_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="legend",
            field=models.TextField(blank=True, null=True, verbose_name="Légende"),
        ),
    ]
