# Generated by Django 2.1.7 on 2019-08-26 13:16

from django.db import migrations, models
import django.db.models.deletion
import zds.gallery
import zds.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_usergallery_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('title', models.CharField(max_length=80, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=80)),
                ('legend', models.CharField(blank=True, max_length=80, null=True, verbose_name='Légende')),
                ('update', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification')),
                ('physical', models.FileField(max_length=200, upload_to=zds.gallery.models.image_path, validators=[zds.gallery.models.SvgValidator()])),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery', verbose_name='Galerie')),
            ],
            options={
                'verbose_name': 'Dessin',
                'verbose_name_plural': 'Dessins',
            },
        ),
    ]
