# Generated by Django 4.2.16 on 2024-11-21 22:39

"""
In production, the column `mode` of the table gallery_usergallery contains both
lower case 'w' and upper case 'W':

SELECT mode, COUNT(*) AS nb FROM gallery_usergallery GROUP BY BINARY mode;
+------+-------+
| mode | nb    |
+------+-------+
| R    |    10 |
| W    | 22693 |
| w    |   603 |
+------+-------+

while only the upper case 'W' is actually recognized (see value of
zds.gallery.models.GALLERY_WRITE). This comes probably from the the permission
modification of galleries when a member unregisters itself: the lower case 'w'
was hard-coded.


This migration changes 'w' to 'W'.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_auto_20191122_1154"),
    ]

    operations = [
        # This WHERE is actually case *in*sensitive, but it will not change
        # the result (just modify more records which don't need it), but
        # having a WHERE which is case-sensitive *and* compatible with both
        # SQLite and MariaDB seems tricky...
        migrations.RunSQL(
            ("UPDATE gallery_usergallery SET mode = 'W' WHERE mode = 'w';"),
        ),
    ]
