# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_commentedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Casquette')),
            ],
            options={
                'verbose_name': 'Casquette',
                'verbose_name_plural': 'Casquettes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='with_hat',
            field=models.CharField(blank=True, max_length=40, verbose_name='Casquette'),
        ),
    ]
