# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 15:08
from __future__ import unicode_literals

from django.db import migrations, models

from zds.utils.models import Tag


def force_unicity(*args, **kwargs):
    duplicates = Tag.objects\
        .values('slug')\
        .order_by()\
        .annotate(min_id=models.Min('id'), count_occurences=models.Count('id'))\
        .filter(count_occurences__gt=1)

    print(' unicity of tag slugs')

    for duplicate in duplicates:
        print('   - Altering duplicates for slug "{}" ({} occurences)'.format(
            duplicate['slug'], duplicate['count_occurences']))

        duplicates_to_modify = Tag.objects\
            .filter(slug=duplicate['slug']).exclude(id=duplicate['min_id'])

        for duplicate_to_modify in duplicates_to_modify:
            duplicate_to_modify.save()  # will change the slug automatically, due to the use of uuslug


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_auto_20170619_1854'),
    ]

    operations = [
        migrations.RunPython(force_unicity),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=30, unique=True, verbose_name='Slug'),
        ),
    ]
