# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Casquette'),
        ),
    ]
