# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_auto_20170822_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Casquette'),
        ),
    ]
