# Generated by Django 1.10.8 on 2017-10-06 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utils", "0017_hat_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="hatrequest",
            name="comment",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Commentaire"),
        ),
        migrations.AddField(
            model_name="hatrequest",
            name="is_granted",
            field=models.NullBooleanField(verbose_name="Est acceptée"),
        ),
        migrations.AddField(
            model_name="hatrequest",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modérateur",
            ),
        ),
        migrations.AddField(
            model_name="hatrequest",
            name="solved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de résolution"),
        ),
    ]
