# Generated by Django 1.10.8 on 2018-05-01 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0019_auto_20180102_1659"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name": "Sous-categorie", "verbose_name_plural": "Sous-categories"},
        ),
    ]
