# Generated by Django 2.2.9 on 2020-02-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_auto_20180826_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip_address',
        ),
    ]
