# Generated by Django 3.2.11 on 2022-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0023_move_potential_spam_to_comment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hatrequest",
            name="is_granted",
            field=models.BooleanField(null=True, verbose_name="Est acceptée"),
        ),
    ]
