# Generated by Django 3.2.13 on 2022-05-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorialv2", "0032_auto_20220507_1519"),
        ("utils", "0024_alter_hatrequest_is_granted"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HelpWriting",
        ),
    ]
