# Generated by Django 4.2.6 on 2024-03-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0025_move_helpwriting"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name="session key"),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                ("expire_date", models.DateTimeField(db_index=True, verbose_name="expire date")),
                ("account_id", models.IntegerField(db_index=True, null=True)),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "abstract": False,
            },
        ),
    ]
