# Generated by Django 4.2.16 on 2024-10-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0026_customsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="update_index_date",
        ),
    ]
